name=MspParser
version=0.3.0
author=Wastl Kraus <derdoktor667>
maintainer=Wastl Kraus <derdoktor667>
sentence=Parses MultiWii Serial Protocol (MSP) messages from any Arduino Stream object.
paragraph=A lightweight, universal, and flexible library for parsing MSP messages from any Arduino Stream object (like Serial, SoftwareSerial, or AltSoftSerial). It is non-blocking, uses a callback mechanism, and supports both MSPv1 and MSPv2. Includes utilities for sending MSP messages and decoding them into human-readable formats.
category=Communication
url=https://github.com/derdoktor667/MspParser
architectures=*
license=MIT